language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tool-25.0.3
    - android-25
    - sys-img-armeabi-v7a-android-25
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
